import { BibleBook } from '@/types';

export const DEFAULT_TRANSLATION = 'web';

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { name: 'Genesis', chapters: 50, category: 'Old Testament' },
  { name: 'Exodus', chapters: 40, category: 'Old Testament' },
  { name: 'Leviticus', chapters: 27, category: 'Old Testament' },
  { name: 'Numbers', chapters: 36, category: 'Old Testament' },
  { name: 'Deuteronomy', chapters: 34, category: 'Old Testament' },
  { name: 'Joshua', chapters: 24, category: 'Old Testament' },
  { name: 'Judges', chapters: 21, category: 'Old Testament' },
  { name: 'Ruth', chapters: 4, category: 'Old Testament' },
  { name: '1 Samuel', chapters: 31, category: 'Old Testament' },
  { name: '2 Samuel', chapters: 24, category: 'Old Testament' },
  { name: '1 Kings', chapters: 22, category: 'Old Testament' },
  { name: '2 Kings', chapters: 25, category: 'Old Testament' },
  { name: '1 Chronicles', chapters: 29, category: 'Old Testament' },
  { name: '2 Chronicles', chapters: 36, category: 'Old Testament' },
  { name: 'Ezra', chapters: 10, category: 'Old Testament' },
  { name: 'Nehemiah', chapters: 13, category: 'Old Testament' },
  { name: 'Esther', chapters: 10, category: 'Old Testament' },
  { name: 'Job', chapters: 42, category: 'Old Testament' },
  { name: 'Psalms', chapters: 150, category: 'Old Testament' },
  { name: 'Proverbs', chapters: 31, category: 'Old Testament' },
  { name: 'Ecclesiastes', chapters: 12, category: 'Old Testament' },
  { name: 'Song of Solomon', chapters: 8, category: 'Old Testament' },
  { name: 'Isaiah', chapters: 66, category: 'Old Testament' },
  { name: 'Jeremiah', chapters: 52, category: 'Old Testament' },
  { name: 'Lamentations', chapters: 5, category: 'Old Testament' },
  { name: 'Ezekiel', chapters: 48, category: 'Old Testament' },
  { name: 'Daniel', chapters: 12, category: 'Old Testament' },
  { name: 'Hosea', chapters: 14, category: 'Old Testament' },
  { name: 'Joel', chapters: 3, category: 'Old Testament' },
  { name: 'Amos', chapters: 9, category: 'Old Testament' },
  { name: 'Obadiah', chapters: 1, category: 'Old Testament' },
  { name: 'Jonah', chapters: 4, category: 'Old Testament' },
  { name: 'Micah', chapters: 7, category: 'Old Testament' },
  { name: 'Nahum', chapters: 3, category: 'Old Testament' },
  { name: 'Habakkuk', chapters: 3, category: 'Old Testament' },
  { name: 'Zephaniah', chapters: 3, category: 'Old Testament' },
  { name: 'Haggai', chapters: 2, category: 'Old Testament' },
  { name: 'Zechariah', chapters: 14, category: 'Old Testament' },
  { name: 'Malachi', chapters: 4, category: 'Old Testament' },
  // New Testament
  { name: 'Matthew', chapters: 28, category: 'New Testament' },
  { name: 'Mark', chapters: 16, category: 'New Testament' },
  { name: 'Luke', chapters: 24, category: 'New Testament' },
  { name: 'John', chapters: 21, category: 'New Testament' },
  { name: 'Acts', chapters: 28, category: 'New Testament' },
  { name: 'Romans', chapters: 16, category: 'New Testament' },
  { name: '1 Corinthians', chapters: 16, category: 'New Testament' },
  { name: '2 Corinthians', chapters: 13, category: 'New Testament' },
  { name: 'Galatians', chapters: 6, category: 'New Testament' },
  { name: 'Ephesians', chapters: 6, category: 'New Testament' },
  { name: 'Philippians', chapters: 4, category: 'New Testament' },
  { name: 'Colossians', chapters: 4, category: 'New Testament' },
  { name: '1 Thessalonians', chapters: 5, category: 'New Testament' },
  { name: '2 Thessalonians', chapters: 3, category: 'New Testament' },
  { name: '1 Timothy', chapters: 6, category: 'New Testament' },
  { name: '2 Timothy', chapters: 4, category: 'New Testament' },
  { name: 'Titus', chapters: 3, category: 'New Testament' },
  { name: 'Philemon', chapters: 1, category: 'New Testament' },
  { name: 'Hebrews', chapters: 13, category: 'New Testament' },
  { name: 'James', chapters: 5, category: 'New Testament' },
  { name: '1 Peter', chapters: 5, category: 'New Testament' },
  { name: '2 Peter', chapters: 3, category: 'New Testament' },
  { name: '1 John', chapters: 5, category: 'New Testament' },
  { name: '2 John', chapters: 1, category: 'New Testament' },
  { name: '3 John', chapters: 1, category: 'New Testament' },
  { name: 'Jude', chapters: 1, category: 'New Testament' },
  { name: 'Revelation', chapters: 22, category: 'New Testament' },
];

export const TRANSLATIONS = [
  { id: 'web', name: 'World English Bible', language: 'English', ttsLang: 'en-US' },
  { id: 'kjv', name: 'King James Version', language: 'English', ttsLang: 'en-US' },
  { id: 'asv', name: 'American Standard Version (1901)', language: 'English', ttsLang: 'en-US' },
  { id: 'bbe', name: 'Bible in Basic English', language: 'English', ttsLang: 'en-US' },
  { id: 'darby', name: 'Darby Bible', language: 'English', ttsLang: 'en-US' },
  { id: 'dra', name: 'Douay-Rheims 1899 American Edition', language: 'English', ttsLang: 'en-US' },
  { id: 'oeb-us', name: 'Open English Bible, US Edition', language: 'English (US)', ttsLang: 'en-US' },
  { id: 'oeb-cw', name: 'Open English Bible, Commonwealth Edition', language: 'English (UK)', ttsLang: 'en-GB' },
  { id: 'webbe', name: 'World English Bible, British Edition', language: 'English (UK)', ttsLang: 'en-GB' },
  { id: 'ylt', name: "Young's Literal Translation (NT only)", language: 'English', ttsLang: 'en-US' },
  { id: 'clementine', name: 'Clementine Latin Vulgate', language: 'Latin', ttsLang: 'la' },
  { id: 'almeida', name: 'João Ferreira de Almeida', language: 'Portuguese', ttsLang: 'pt-PT' },
  { id: 'rccv', name: 'Protestant Romanian Corrected Cornilescu Version', language: 'Romanian', ttsLang: 'ro-RO' },
  { id: 'cuv', name: 'Chinese Union Version', language: 'Chinese', ttsLang: 'zh-TW' },
  { id: 'bkr', name: 'Bible kralická', language: 'Czech', ttsLang: 'cs-CZ' },
  { id: 'cherokee', name: 'Cherokee New Testament', language: 'Cherokee', ttsLang: 'chr' },
  { id: 'synodal', name: 'Russian Synodal Translation', language: 'Russian', ttsLang: 'ru-RU' },
] as const;

export const BIBLE_BOOK_ID_BY_NAME: Record<string, string> = {
  Genesis: 'GEN',
  Exodus: 'EXO',
  Leviticus: 'LEV',
  Numbers: 'NUM',
  Deuteronomy: 'DEU',
  Joshua: 'JOS',
  Judges: 'JDG',
  Ruth: 'RUT',
  '1 Samuel': '1SA',
  '2 Samuel': '2SA',
  '1 Kings': '1KI',
  '2 Kings': '2KI',
  '1 Chronicles': '1CH',
  '2 Chronicles': '2CH',
  Ezra: 'EZR',
  Nehemiah: 'NEH',
  Esther: 'EST',
  Job: 'JOB',
  Psalms: 'PSA',
  Proverbs: 'PRO',
  Ecclesiastes: 'ECC',
  'Song of Solomon': 'SNG',
  Isaiah: 'ISA',
  Jeremiah: 'JER',
  Lamentations: 'LAM',
  Ezekiel: 'EZK',
  Daniel: 'DAN',
  Hosea: 'HOS',
  Joel: 'JOL',
  Amos: 'AMO',
  Obadiah: 'OBA',
  Jonah: 'JON',
  Micah: 'MIC',
  Nahum: 'NAM',
  Habakkuk: 'HAB',
  Zephaniah: 'ZEP',
  Haggai: 'HAG',
  Zechariah: 'ZEC',
  Malachi: 'MAL',
  Matthew: 'MAT',
  Mark: 'MRK',
  Luke: 'LUK',
  John: 'JHN',
  Acts: 'ACT',
  Romans: 'ROM',
  '1 Corinthians': '1CO',
  '2 Corinthians': '2CO',
  Galatians: 'GAL',
  Ephesians: 'EPH',
  Philippians: 'PHP',
  Colossians: 'COL',
  '1 Thessalonians': '1TH',
  '2 Thessalonians': '2TH',
  '1 Timothy': '1TI',
  '2 Timothy': '2TI',
  Titus: 'TIT',
  Philemon: 'PHM',
  Hebrews: 'HEB',
  James: 'JAS',
  '1 Peter': '1PE',
  '2 Peter': '2PE',
  '1 John': '1JN',
  '2 John': '2JN',
  '3 John': '3JN',
  Jude: 'JUD',
  Revelation: 'REV',
};

export const THEME_COLORS = {
  light: {
    bg: 'bg-white',
    text: 'text-gray-900',
    secondary: 'text-gray-600',
    border: 'border-gray-100',
    highlight: 'bg-yellow-100',
  },
  dark: {
    bg: 'bg-zinc-950',
    text: 'text-zinc-100',
    secondary: 'text-zinc-400',
    border: 'border-zinc-800',
    highlight: 'bg-yellow-900/30',
  },
  sepia: {
    bg: 'bg-[#f4ecd8]',
    text: 'text-[#433422]',
    secondary: 'text-[#6d5b4b]',
    border: 'border-[#e0d6c3]',
    highlight: 'bg-[#d8c5a2]',
  },
};
